vavilov_pedigree/urls.py
from django.conf.urls import url, include
from vavilov_pedigree.views.details import (AccessionDetail, AssayDetail,
                                            PlantDetail, SeedLotDetail)
from vavilov_pedigree.views.search import search, CrossExperiments

pedigree_urlpatterns = [
    url(r'^assays/(?P<name>.+)/$', AssayDetail, name='assay-detail'),
    url(r'^seedlots/(?P<name>.+)/$', SeedLotDetail.as_view(), name='seedlot-detail'),
    url(r'^accessions/(?P<accession_number>.+)/$', AccessionDetail.as_view(), name='accession-detail'),
    url(r'^plants/(?P<plant_name>.+)/$', PlantDetail.as_view(), name='plant-detail'),
    url(r'^search/$', search, name='search'),
    url(r'^cross_experiments/$', CrossExperiments.as_view(), name='cross_exp-list')
]

urlpatterns = [
    url(r'', include(pedigree_urlpatterns, namespace='pedigree')),
]

vavilov_pedigree/views/search.py
from django import forms
from django.db.models import Q
from vavilov_pedigree.models import (Accession, Plant, SeedLot,
                                     CrossExperimentSeedLot,
                                     filter_cross_experiments)
from vavilov_pedigree.views.tables import (plant_to_table, seedlot_to_table,
                                           accession_to_table, CrossTable)
from vavilov.views.generic import (search_criteria_to_get_parameters,
                                   SearchListView)
from django.template.context_processors import csrf
from django.shortcuts import render_to_response


class SearchForm(forms.Form):
    anything = forms.CharField(label='Pedigree data', required=False)


def search(request):
    context = {'request': request}
    context['user'] = request.user
    context.update(csrf(request))
    content_type = None  # default
    getdata = False

    if request.method == 'POST':
        request_data = request.POST
    elif request.method == 'GET':
        request_data = request.GET
        getdata = True
    else:
        request_data = None
    template = 'vavilov_pedigree/search.html'
    if request_data:
        form = SearchForm(request_data)
        if form.is_valid():
            search_criteria = form.cleaned_data
            search_criteria = dict([(key, value) for key, value in
                                    search_criteria.items() if value])
            context['search_criteria'] = search_criteria
            value = form.cleaned_data['anything']

            # do search
            plants = Plant.objects.filter(Q(plant_name__icontains=value) |
                                          Q(seed_lot__name__icontains=value))
            context['plants'] = plant_to_table(plants, request)

            seedlots = SeedLot.objects.filter(Q(name__icontains=value) |
                                              Q(accession__accession_number__icontains=value))
            context['seedlots'] = seedlot_to_table(seedlots, request)
            Accession.objects.all
            accessions = Accession.objects.filter(Q(accession_number__icontains=value) |
                                                  Q(collecting_number__icontains=value))

            context['accessions'] = accession_to_table(accessions, request)
            if not getdata:
                context['criteria'] = search_criteria_to_get_parameters(search_criteria)
    else:
        form = SearchForm()

    context['form'] = form
    return render_to_response(template, context, content_type=content_type)


class SearchCrossForm(forms.Form):
    description = forms.CharField(required=False,)
    father = forms.CharField(required=False, label='Father plant code or accession')
    mother = forms.CharField(required=False, label='Mother plant code or accession')
    offspring = forms.CharField(required=False, label='Offspring seedlot code or accession')


class CrossExperiments(SearchListView):
    model = CrossExperimentSeedLot
    template_name = 'vavilov_pedigree/cross_exp_list.html'
    form_class = SearchCrossForm
    table = CrossTable
    redirect_in_one = False
    detail_view_name = ''

    def get_queryset(self, **kwargs):
        search_criteria = kwargs['search_criteria']
        return filter_cross_experiments(search_criteria)

vavilov_pedigree/templates/vavilov_pedigree/accession.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}
{% load extras %}
{% block page_spec_js %}{% include 'vavilov/galleria_head.html' %}{% endblock page_spec_js %}
{% block title %}Accession {{accession.accession_number}} {% endblock title %}
{% block content %}
<section >
    <h2> Passport data for {{accession.accession_number }}</h2>
    <div class='accession_table'>
	    <table class="data_table">
	    <tr>
	        <td class="key">Accession number :</td>
	        <td class="value">{{accession.accession_number}}</td>
	    </tr>
	    {% if accession.donor_accession %}
	        <tr>
	          <td class="key">Donor</td>
	          <td class="value">{{ accession.donor_accession|link_if_url:accession.donor_accession}}}</td>
	        </tr>
	    {% endif %}
	    {%if accession.collecting_number %}
	        <tr>
	          <td class="key">Collecting number</td>
	          <td class="value">{{ accession.collecting_number}}</td>
	        </tr>
	    {% endif %}
	    {% if accession.duplicated_accessions %}
	      {% with dup_accs=accession.duplicated_accessions%}
	        <tr>
	            <td class="key">Duplicated accessions in other databases</td>
	            <td class="value"></td>
	        </tr>
	                {% for dup_acc in dup_accs %}
	                <tr>
	                    <td></td>
	                    <td>{{dup_acc|link_if_url:dup_acc}}</td>
	                 </tr>
	                 {% endfor %}
	      {% endwith %}
	    {% endif %}
	    {% if accession.organism %}
	       <tr>
                <td class="key">Organism</td>
                <td class="value">{{ accession.organism }}</td>
            </tr>
	    {% endif %}
	    </table>
	</div>
	<hr class='empty_line'>
    {% if accession.passport%}
        {% with pass=accession.passport %}
	        <div id="passport_data_map">
		        <div class='passport_table'>
		            <table class="data_table">
		            {% for shown_str, prop_content in pass.data_to_show.items %}
		              {% if prop_content %}
		                <tr>
		                    <td  class="key">{{shown_str}}</td>
		                    <td>{{ prop_content}}</td>
		                </tr>
		              {% endif %}     
		            {% endfor %}
		            </table>
		        </div>
		        {% with location=pass.location %}
		            {% include 'vavilov/googlemap.html' %}
		        {% endwith %}
		    </div>
        {% endwith %}
    {% endif %}     	    
</section>
    {% if assays %}
        <section class='clear'>    
            <hr class='empty_line'>
            <h3> This Accession has been used in these assays</h3>
            {% render_table assays %}
            <span class="clear"></span>
	</section>
    {% endif %}

    {% if observations %}
	<section class='clear'>
        	<hr class='empty_line'>
	        <h3> Observations on this accession </h3>
	        {% render_table observations %}
	        {% include 'vavilov/download_observations.html' with search_criteria=obs_search_criteria %}
	        <span class="clear"></span>
	</section>
    {% endif %}
    {% include 'vavilov/galleria_js.html' with images=obs_images %}
    {% if seedlots %}
        <H3> Seed lots belongint to this accession</h3>
        {% render_table seedlots %}
    
    {% endif %}

    
{% endblock %}

vavilov_pedigree/templates/vavilov_pedigree/accession_detail.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}
{% load extras %}
{% block page_spec_js %}{% include 'vavilov/galleria_head.html' %}{% endblock page_spec_js %}
{% block title %}Accession {{accession.accession_number}} {% endblock title %}
{% block content %}
<section >
    <h2> Passport data for {{accession.accession_number }}</h2>
    <div class='accession_table'>
	    <table class="data_table">
	    <tr>
	        <td class="key">Accession number :</td>
	        <td class="value"><a href='{% url 'accession-detail' accession.accession_number %}'>{{accession.accession_number}}</a></td>
	    </tr>
	    {% if accession.donor_accession %}
	        <tr>
	          <td class="key">Donor</td>
	          <td class="value">{{ accession.donor_accession|link_if_url:accession.donor_accession}}}</td>
	        </tr>
	    {% endif %}
	    {%if accession.collecting_number %}
	        <tr>
	          <td class="key">Collecting number</td>
	          <td class="value">{{ accession.collecting_number}}</td>
	        </tr>
	    {% endif %}
	    {% if accession.duplicated_accessions %}
	      {% with dup_accs=accession.duplicated_accessions%}
	        <tr>
	            <td class="key">Duplicated accessions in other databases</td>
	            <td class="value"></td>
	        </tr>
	                {% for dup_acc in dup_accs %}
	                <tr>
	                    <td></td>
	                    <td>{{dup_acc|link_if_url:dup_acc}}</td>
	                 </tr>
	                 {% endfor %}
	      {% endwith %}
	    {% endif %}
	    {% if accession.organism %}
	       <tr>
                <td class="key">Organism</td>
                <td class="value">{{ accession.organism }}</td>
            </tr>
	    {% endif %}
	    </table>
	</div>
	<hr class='empty_line'>
    {% if accession.passport%}
        {% with pass=accession.passport %}
	        <div id="passport_data_map">
		        <div class='passport_table'>
		            <table class="data_table">
		            {% for shown_str, prop_content in pass.data_to_show.items %}
		              {% if prop_content %}
		                <tr>
		                    <td  class="key">{{shown_str}}</td>
		                    <td>{{ prop_content}}</td>
		                </tr>
		              {% endif %}
		            {% endfor %}
		            </table>
		        </div>
		        {% with location=pass.location %}
		            {% include 'vavilov/googlemap.html' %}
		        {% endwith %}
		    </div>
        {% endwith %}
    {% endif %}
</section>
    {% if assays %}
        <section class='clear'>
            <hr class='empty_line'>
            <h3> This Accession has been used in these assays</h3>
            {% render_table assays %}
            <span class="clear"></span>
	</section>
    {% endif %}

    {% if observations %}
	<section class='clear'>
        	<hr class='empty_line'>
	        <h3> Observations on this accession </h3>
	        {% render_table observations %}
	        {% include 'vavilov/download_observations.html' with search_criteria=obs_search_criteria %}
	        <span class="clear"></span>
	</section>
    {% endif %}
    {% if obs_images %}
        {% include 'vavilov/galleria_js.html' with images=obs_images %}
    {% endif %}
    {% if seedlots %}
        <hr class='empty_line'>
        <H3> Seed lots belongint to this accession</h3>
        {% render_table seedlots %}

    {% endif %}
    {% if cross_experiments %}
        <hr class='empty_line'>
        <H3> This accession is part of this cross_experiments</h3>
        {% render_table cross_experiments %}

    {% endif %}

{% endblock %}

vavilov_pedigree/templates/vavilov_pedigree/assay.html
{% extends "base.html" %}
{% load staticfiles %}
{% load render_table from django_tables2 %}
{% block title %}Accession {{ accession.code}} {% endblock title %}
{% block content %}

<section id=central_column>
    <h2>Assay {{assay.name}} </h2>
    <div class='accession_table'>
        <table class="data_table">
            {% if assay.start_date %}
                <tr>
                    <td class="key">Start Date :</td>
                    <td class="value">{{assay.start_date}}</td>
                </tr>
            {% endif%}
            {% if assay.end_date %}
                <tr>
                    <td class="key">End Date :</td>
                    <td class="value">{{assay.end_date}}</td>
                </tr>
            {% endif%}
            {% for key, value in assay.props.items%}
                <tr>
                    <td class="key">{{ key }}</td>
                    <td class="value">{{value}}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
</section>
{% if plants %}
    <hr class='empty_line'>
	<h3> Plants on this assay </h3>
	{% render_table plants %}
	<span class="clear"></span>
{% endif %}

{% if observations %}
    <hr class='empty_line'>
	<h3> Observations on this assay </h3>
	{% render_table observations %}
	{% include 'vavilov/download_observations.html' with search_criteria=obs_search_criteria %}
	<span class="clear"></span>
{% endif %}

{#{% include 'vavilov/galleria_js.html' with images=obs_images %}#}

{% endblock %}

vavilov_pedigree/templates/vavilov_pedigree/assay_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load render_table from django_tables2 %}
{% block title %}Accession {{ accession.code}} {% endblock title %}
{% block content %}

<section id=central_column>
    <h2>Assay {{assay.name}} </h2>
    <div class='accession_table'>
        <table class="data_table">
            {% if assay.start_date %}
                <tr>
                    <td class="key">Start Date :</td>
                    <td class="value">{{assay.start_date}}</td>
                </tr>
            {% endif%}
            {% if assay.end_date %}
                <tr>
                    <td class="key">End Date :</td>
                    <td class="value">{{assay.end_date}}</td>
                </tr>
            {% endif%}
            {% for key, value in assay.props.items%}
                <tr>
                    <td class="key">{{ key }}</td>
                    <td class="value">{{value}}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
</section>
{% if plants %}
    <hr class='empty_line'>
	<h3> Plants on this assay </h3>
	{% render_table plants %}
	<span class="clear"></span>
{% endif %}

{% if observations %}
    <hr class='empty_line'>
	<h3> Observations on this assay </h3>
	{% render_table observations %}
	{% include 'vavilov/download_observations.html' with search_criteria=obs_search_criteria %}
	<span class="clear"></span>
{% endif %}

{#{% include 'vavilov/galleria_js.html' with images=obs_images %}#}

{% endblock %}

vavilov_pedigree/templates/vavilov_pedigree/cross_exp_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load extras %}
{% load render_table from django_tables2 %}
{% block title %}Search cross experiments {% endblock title %}
{% block content %}
    {% if search_criteria and not object_list%}
      <p>No cross experiments found</p>
    {% endif %}
    
    {% if object_list %}
       <h3> Search result</h3>
      {% render_table object_list %}
      {% url 'cross_exp-list' as base_url %}
      {% load urlbuilder %}
      <div class=download_csv>
          <ul> 
              <li>Download</li>
              <li><a href='{% build_url base_url search_criteria download_search=True,format=csv%}' download><img src="{% static "vavilov/style/images/csv_icon.png"%}"/></a></li>
              <li><a href='{% build_url base_url search_criteria download_search=True,format=excel%}' download><img src="{% static "vavilov/style/images/xls_icon.png"%}"/></a></li>
           </ul>
      </div>
    {% else %}
     <h3> Search cross experiments</h3>
       <form action='' method="post">{% csrf_token %}
           <div class='search_form'>
           {{ form.as_table }}
           </div>
           <input type="submit" value="Search" />
      </form>
    {% endif %}
{% endblock %}

vavilov_pedigree/templates/vavilov_pedigree/plant.html
{% extends "base.html" %}
{% load staticfiles %}
{% load extras %}
{% block page_spec_js %}{% include 'vavilov/galleria_head.html' %}{% endblock page_spec_js %}
{% load render_table from django_tables2 %}
{% block title %}Plant {{ plant.plant_name}} {% endblock title %}
{% block content %}
<h1> Plant {{ plant.plant_name}} </h1>
<div class="table-container">
	<table class="data_table">
	    <tr>
	        <td class="key">Accession number :</td>
	        <td class="value"><a href='{% url 'pedigree_accession_view' plant.seed_lot.accession.accession_number %}'>{{plant.seed_lot.accession.accession_number}}</a></td>
	    </tr>
	    {% if plant.experimental_field %}
	    <tr>
	        <td class="key">Experimental field :</td>
	        <td class="value">{{plant.experimental_field}}</td>
	    </tr>
	    {% endif %}
	    {% if plant.row %}
	    <tr>
	        <td class="key">Row :</td>
	        <td class="value">{{plant.row}}</td>
	    </tr>
	    {% endif %}
	    {% if plant.column %}
	    <tr>
	        <td class="key">Column :</td>
	        <td class="value">{{plant.column}}</td>
	    </tr>
	    {% endif %}
	    {% if plant.pot_number %}
	    <tr>
	        <td class="key">Pot number :</td>
	        <td class="value">{{plant.pot_number}}</td>
	    </tr>
	    {% endif %}
	    <tr>
            <td class="key">Seed_lot :</td>
            <td class="value"><a href='{% url 'pedigree_seedlot_view' plant.seed_lot.name %}'>{{plant.seed_lot.name}}</a></td>
        </tr>
	</table>
</div>
{% if clones %}
    <h3> Clones of this plant </h3>
    {% render_table clones %}
{% endif %}

{% if assays %}
    <hr class='empty_line'>
	<h3> This plant has been used in these assays</h3>
	{% render_table assays %}
{% endif %}
<span class="clear"></span>


{% endblock %}

vavilov_pedigree/templates/vavilov_pedigree/plant_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load extras %}
{% block page_spec_js %}{% include 'vavilov/galleria_head.html' %}{% endblock page_spec_js %}
{% load render_table from django_tables2 %}
{% block title %}Plant {{ plant.plant_name}} {% endblock title %}
{% block content %}
<h1> Plant {{ plant.plant_name}} </h1>
<div class="table-container">
	<table class="data_table">
	    <tr>
	        <td class="key">Accession number :</td>
	        <td class="value"><a href='{% url 'pedigree:accession-detail' plant.seed_lot.accession.accession_number %}'>{{plant.seed_lot.accession.accession_number}}</a></td>
	    </tr>
	    {% if plant.experimental_field %}
	    <tr>
	        <td class="key">Experimental field :</td>
	        <td class="value">{{plant.experimental_field}}</td>
	    </tr>
	    {% endif %}
	    {% if plant.row %}
	    <tr>
	        <td class="key">Row :</td>
	        <td class="value">{{plant.row}}</td>
	    </tr>
	    {% endif %}
	    {% if plant.column %}
	    <tr>
	        <td class="key">Column :</td>
	        <td class="value">{{plant.column}}</td>
	    </tr>
	    {% endif %}
	    {% if plant.pot_number %}
	    <tr>
	        <td class="key">Pot number :</td>
	        <td class="value">{{plant.pot_number}}</td>
	    </tr>
	    {% endif %}
	    <tr>
            <td class="key">Seed_lot :</td>
            <td class="value"><a href='{% url 'pedigree:seedlot-detail' plant.seed_lot.name %}'>{{plant.seed_lot.name}}</a></td>
        </tr>
	</table>
</div>
{% if clones %}
    <h3> Clones of this plant </h3>
    {% render_table clones %}
{% endif %}

{% if assays %}
    <hr class='empty_line'>
	<h3> This plant has been used in these assays</h3>
	{% render_table assays %}
{% endif %}
<span class="clear"></span>


{% endblock %}

vavilov_pedigree/templates/vavilov_pedigree/plant_pedigree.html
<a href='{% url 'pedigree:plant-detail' plant.plant_name %}'>{{plant.plant_name}}</a>
    (Comming from seedlot:<a href='{% url 'pedigree:seedlot-detail' plant.seed_lot.name %}'>{{plant.seed_lot.name}}</a>
    {% if plant.seed_lot.accession %}
        (That belongs to accession: <a href='{% url 'pedigree:accession-detail' plant.seed_lot.accession.accession_number %}'>{{plant.seed_lot.accession.accession_number}}</a>)
    {% endif %})

vavilov_pedigree/templates/vavilov_pedigree/search.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}
{% load extras %}
{% block page_spec_js %}{% include 'vavilov/galleria_head.html' %}{% endblock page_spec_js %}
{% block title %}Accession {{accession.accession_number}} {% endblock title %}
{% block content %}
<section>
<fieldset>
  <legend>Search:</legend>
  <form action='' method='POST'>{% csrf_token %}
    {{form.as_table}}
    <input type='submit' value='search'>
  </form>
</fieldset>
<hr class='empty_line'>

{% if request.method != 'GET' and not plants and not seedlots and not accessions%}
<p> Nothing found</p>
{% endif%}

{% if accessions %}
    <h3> Accessions: </h3>
    {% render_table accessions %}
    <hr class='empty_line'>
{% endif %}

{% if seedlots %}
    <h3> Seedlots: </h3>
    {% render_table seedlots %}
    <hr class='empty_line'>
{% endif %}

{% if plants %}
    <h3> Plants </h3>
    {% render_table plants %}
    <hr class='empty_line'>    
{% endif %}

</section>
{% endblock %}

vavilov_pedigree/templates/vavilov_pedigree/seedlot.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}
{% load extras %}
{% block title %}Seedlot {{seedlot.name}} {% endblock title %}
{% block content %}
<section >
    <div class='accession_table'>
    <h2> Seed Lot  {{seedlot.name }}</h2>
	    <table class="data_table">
		    <tr>
	            <td class="key">Name :</td>
	            <td class="value">{{seedlot.name}}</td>
	        </tr>
	        <tr>
                <td class="key">Description :</td>
                <td class="value">{{seedlot.description}}</td>
            </tr>
		    <tr>
		        <td class="key">Accession :</td>
		        <td class="value"><a href='{% url 'pedigree_accession_view' seedlot.accession.accession_number %}'>{{seedlot.accession.accession_number}}</a></td>
		    </tr>
		    {% if seedlot.num_seeds %}
                <tr>
                    <td class="key">num Seeds :</td>
                    <td class="value">{{seedlot.num_seeds}}</td>
                </tr>
            {% endif %}
            
            {% if seedlot.mothers %}
                <tr>
                    <td class="key"> Mothers :</td>
                    {% with seedlot.mothers|first as plant%}
                        <td class="value">{% include 'vavilov_pedigree/plant_pedigree.html'%}</td>
                    {% endwith %}
                    {% for plant in seedlot.mothers|slice:"1:" %}
                       <tr>
                        <td></td>  
                        <td class="value">{% include 'vavilov_pedigree/plant_pedigree.html'%}</td>
                       </tr>
                    {% endfor %}
                </tr>
            {% endif %}
            
		    {% if seedlot.fathers %}
			    <tr>
                    <td class="key"> Fathers :</td>
                    {% with seedlot.fathers|first as plant%}
                        <td class="value">{% include 'vavilov_pedigree/plant_pedigree.html'%}</td>
                    {% endwith %}
                    {% for plant in seedlot.fathers|slice:"1:" %}
                       <tr>
                        <td></td>  
                        <td class="value">{% include 'vavilov_pedigree/plant_pedigree.html'%}</td>
                       </tr>
                    {% endfor %}
                </tr>
	        {% endif %}
	        
	        
		</table>
	</div>
</section>


{% if accession.seed_lots %}
<ul>{{ variable }}
{% for seed_lot in accession.seed_lots %}
    <li><a href='/pedigree/seedlot/{{seed_lot}}'>{{seed_lot}}</a></li>
{% endfor %}
</ul>
{% endif %}

    
{% endblock %}

vavilov_pedigree/templates/vavilov_pedigree/seedlot_detail.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}
{% load extras %}
{% block title %}Seedlot {{seedlot.name}} {% endblock title %}
{% block content %}
<section >
    <div class='accession_table'>
    <h2> Seed Lot  {{seedlot.name }}</h2>
	    <table class="data_table">
		    <tr>
	            <td class="key">Name :</td>
	            <td class="value">{{seedlot.name}}</td>
	        </tr>
	        <tr>
                <td class="key">Description :</td>
                <td class="value">{{seedlot.description}}</td>
            </tr>
		    <tr>
		        <td class="key">Accession :</td>
		        <td class="value"><a href='{% url 'pedigree:accession-detail' seedlot.accession.accession_number %}'>{{seedlot.accession.accession_number}}</a></td>
		    </tr>
		    {% if seedlot.num_seeds %}
                <tr>
                    <td class="key">num Seeds :</td>
                    <td class="value">{{seedlot.num_seeds}}</td>
                </tr>
            {% endif %}
            
            {% if seedlot.mothers %}
                <tr>
                    <td class="key"> Mothers :</td>
                    {% with seedlot.mothers|first as plant%}
                        <td class="value">{% include 'vavilov_pedigree/plant_pedigree.html'%}</td>
                    {% endwith %}
                    {% for plant in seedlot.mothers|slice:"1:" %}
                       <tr>
                        <td></td>  
                        <td class="value">{% include 'vavilov_pedigree/plant_pedigree.html'%}</td>
                       </tr>
                    {% endfor %}
                </tr>
            {% endif %}
            
		    {% if seedlot.fathers %}
			    <tr>
                    <td class="key"> Fathers :</td>
                    {% with seedlot.fathers|first as plant%}
                        <td class="value">{% include 'vavilov_pedigree/plant_pedigree.html'%}</td>
                    {% endwith %}
                    {% for plant in seedlot.fathers|slice:"1:" %}
                       <tr>
                        <td></td>  
                        <td class="value">{% include 'vavilov_pedigree/plant_pedigree.html'%}</td>
                       </tr>
                    {% endfor %}
                </tr>
	        {% endif %}
	        
		</table>
	</div>
{% if cross_experiments %}
    <hr class='empty_line'>
    <H3> This seed lot has been used  or is a result of this cross_experiments</h3>
    {% render_table cross_experiments %}
{% endif %}
</section>


{% if accession.seed_lots %}
<ul>{{ variable }}
{% for seed_lot in accession.seed_lots %}
    <li><a href='/pedigree/seedlot/{{seed_lot}}'>{{seed_lot}}</a></li>
{% endfor %}
</ul>
{% endif %}

    
{% endblock %}